### ISSUE TITLE
Print PDF is rendering blank

### ISSUE THREAD

**Issue by ItsJonQ** [WordPress/slides#11]
<img width="1432" alt="Screen Shot 2019-10-31 at 9 39 54 PM" src="https://user-images.githubusercontent.com/2322354/67998575-0b98d400-fc27-11e9-9509-4661217fb25b.png">

After digging (and checking out how Reveal.js's print PDF page is working)...

I was able to make **some** progress. But not there yet.
CSS is definitely part of the problem.

### `display`
The inline styles within the header `<style>` is overriding the `display: block` which is coming from the `pdf.min.css` styles.

The print styles require the `<div class="slide" />` to be `display: block` (not `display: flex`).

There's still rendering issues, but it's a start I think!

### `position`(?)
The other piece is positioning. It's not aligning where it should. The content is snapping to the top. I *think* the non-PDF version was aligning via `flex`, which is awesome (I would have done the same). But maybe Reveal.js doesn't know how to handle this properly when it tries to render the print-friendly version.

🤔 

That's all I have for now!

**Comment by ellatrix** [comment]
I'm going to rework this very soon. Thanks for the issue!

**Comment by ellatrix** [comment]
Going to close as it is mostly fixed, let's open separate issues for block rendering issues in PDF.
