### ISSUE TITLE
Please separate 'slide' string for Plugin/Transition effect

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/slides#13]
The localization strings are the same for the name of the plugin and the transition effect 'slide'. Please separate them to allow correct translation of both terms (different in lot of languages)
<img width="267" alt="captura 2019-11-03 a las 13 39 14" src="https://user-images.githubusercontent.com/1914800/68085280-a23fdd80-fe3f-11e9-969b-f6d1bcccd62c.png">
<img width="970" alt="captura 2019-11-03 a las 13 39 45" src="https://user-images.githubusercontent.com/1914800/68085281-a5d36480-fe3f-11e9-92b7-f84bb5f0e961.png">

**Comment by fernandotellado** [comment]
Issue for correct translations

**Comment by pedro-mendonca** [comment]
The issue for now is that the plugin name is 'Slide'.
Renaming it to the correct name 'Slides' as in #15 will separate it for now, as there is no translation string in the UI with 'Slides'.
If in the future there is some 'Slides' in the UI, it will need to be wrapped in a _x() to avoid conflicting with the plugin name, that shouldn't be translated.

**Comment by fernandotellado** [comment]
I agree that the plugin name must not be translated but the type of transition 'slide' yes

**Comment by pedro-mendonca** [comment]
The thing is that the slug is 'slide' but the plugin is named 'Slides' in this repo and on wp.org.
Hopefully @ellatrix can clarify it :)

**Comment by ellatrix** [comment]
Yes, let's name it "Slides". Too bad the plugin url `slides` wasn't available, so I considered naming it "Slide" for a moment to reflect the url.

**Comment by ellatrix** [comment]
Thanks for the report, I'll adjust asap.
